POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
	"login": "some long login here",
	"email": "some_long_login_here@example.com",
	"registrationDate": "01/09/2022"
}

#######
GET http://localhost:3000/users HTTP/1.1

#######
GET http://localhost:3000/users/636d06b30e7ea72f756bf4b6 HTTP/1.1

#######
PUT http://localhost:3000/users/636d06b30e7ea72f756bf4b6 HTTP/1.1
content-type: application/json

{
	"login": "seba2",
	"email": "seba2@example.com",
	"registrationDate": "11/11/2022"
}